<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-N1KMP2C8" failures="1" tests="1" name="ObjRepository.CreateLeadWithCampaignTest" time="29.745" errors="0" timestamp="2025-06-28T10:06:29 IST" skipped="0">
  <testcase classname="ObjRepository.CreateLeadWithCampaignTest" name="createLeadWithCpgnTest" time="29.745">
    <failure message="The following asserts failed:
	Failed to create the leadRobot expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Failed to create the leadRobot expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at ObjRepository.CreateLeadWithCampaignTest.createLeadWithCpgnTest(CreateLeadWithCampaignTest.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[========createLeadWithCpgnTest==STARTED==
========createLeadWithCpgnTest==FAILED==]]>
    </system-out>
  </testcase> <!-- createLeadWithCpgnTest -->
  <system-out>
    <![CDATA[Report Configuration
Report Configuration
Establish the DB connectivity
Pre-condition
Launching the browser
Logged in to NCRM
========CreateCpgnTest==STARTED==
========CreateCpgnTest==FAILED==
Logged out successfully
Browser closed
Launching the browser
Logged in to NCRM
========createCampwithDateTest==STARTED==
========createCampwithDateTest==SUCCESS==
Logged out successfully
Browser closed
Launching the browser
Logged in to NCRM
========createLeadWithCpgnTest==STARTED==
========createLeadWithCpgnTest==FAILED==
Logged out successfully
Browser closed
Launching the browser
Logged in to NCRM
========createProductTest==STARTED==
========createProductTest==SUCCESS==
Logged out successfully
Browser closed
Post-condition
Disconnect DB]]>
  </system-out>
</testsuite> <!-- ObjRepository.CreateLeadWithCampaignTest -->
